### ISSUE TITLE
少了太多个文件

### ISSUE THREAD

**Issue by mosentest** [vpaliyX/Melophile#10]
少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件少了太多个文件

**Comment by vpaliy** [comment]
???????????????????????????????????????????????????????????

**Comment by mosentest** [comment]
When I compile, less of a lot of classes, you can commit all the complete source for a moment?

**Comment by vpaliy** [comment]
Yes, there's one class that is excluded - the class that contains the API key for streaming music. Sorry, I can't expose that key.
