### ISSUE TITLE
Error:(8, 23) error: cannot find symbol class Config

### ISSUE THREAD

**Issue by Jaymin-Bhadani** [vpaliyX/Melophile#2]
import com.vpaliy.data.Config;

**Comment by vpaliy** [comment]
This class keeps my `client_id`, `client_secret`, and `redirect_uri`, so I can't expose that.

**Comment by Jaymin-Bhadani** [comment]
bro the currently api not available in website && what i should add in redirect_uri ?

**Comment by vpaliy** [comment]
I'm sorry but I can't expose my credentials. If you want to try the app, you can download the APK from [here](https://github.com/vpaliyX/CasptoneProject/blob/master/app/app-release.apk). But keep in mind that it's not the same project (that one uses Loaders API instead  of RxJava2, I wasn't allowed to use RxJava2). And I will delete the repository once it gets accepted.

**Comment by vpaliy** [comment]
The other repository is for Udacity.

**Comment by Jaymin-Bhadani** [comment]
i see  that apk but cant login with my soundcloud id password?
