### ISSUE TITLE
Cant able to build the project

### ISSUE THREAD

**Issue by hirenkharsani** [vpaliyX/Melophile#3]
**Error:(8, 23) error: cannot find symbol class Config** this error appears whenever i tried to build apk

**Comment by vpaliy** [comment]
I can't expose this file because it contains my credentials from SoundCloud. You will need to use yours.

**Comment by hirenkharsani** [comment]
its ok but how can I generate mine ? Will you help ?

**Comment by vpaliy** [comment]
please refer to #4
